# background_blur 20
# background_opacity 0.95
cursor_trail 0

copy_on_select yes

cursor_shape block

enable_audio_bell no

font_family IosevkaTerm NFM Light

font_size 22.0

disable_ligatures never

hide_window_decorations yes

map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0

shell_integration no-cursor
shell /usr/bin/zsh

confirm_os_window_close 0

window_border_width 0
window_margin_width 0


# Kanagawa
# foreground                      #dcd7ba
# background                      #1f1f28
# selection_foreground            #c8c093
# selection_background            #2d4f67
# #: Cursor colors

# cursor                          #c8c093

# #: URL underline color when overing with mouse

# url_color                       #72a7bc

# #: Tab bar colors

# active_tab_foreground           #c8c093
# active_tab_background           #1f1f28
# inactive_tab_foreground         #727169
# inactive_tab_background         #1f1f28

# #: The basic 16 colors
# #: black
# color0  #16161d
# color8  #727169

# #: red
# color1  #c34043
# color9  #e82424

# #: green
# color2  #76946a
# color10 #98bb6c

# #: yellow
# color3  #c0a36e
# color11 #e6c384

# #: blue
# color4  #7e9cd8
# color12 #7fb4ca

# #: magenta
# color5  #957fb8
# color13 #938aa9

# #: cyan
# color6  #6a9589
# color14 #7aa89f

# #: white
# color7  #c8c093
# color15 #dcd7ba

# color16 #ffa066
# color17 #ff5d62
#

# Monochrome theme
background            #000000
foreground            #FFFFFF
cursor                #FFFFFF

# black
color0                #000000
color8                #444444

# red
color1                #666666
color9                #AAAAAA

# green
color2                #666666
color10               #AAAAAA

# yellow
color3                #666666
color11               #AAAAAA

# blue
color4                #666666
color12               #AAAAAA

# magenta
color5                #666666
color13               #AAAAAA

# cyan
color6                #666666
color14               #AAAAAA

# white
color7                #BBBBBB
color15               #FFFFFF

# # belafonte day
# background            #d4ccb9
# foreground            #45363b
# cursor                #45363b
# selection_background  #958b83
# color0                #20111a
# color8                #5e5252
# color1                #bd100d
# color9                #bd100d
# color2                #858062
# color10               #858062
# color3                #e9a448
# color11               #e9a448
# color4                #416978
# color12               #416978
# color5                #96522b
# color13               #96522b
# color6                #98999c
# color14               #98999c
# color7                #958b83
# color15               #d4ccb9
# selection_foreground #d4ccb9


startup_session ~/.config/kitty/kitty-startup.session
