#!/usr/bin/bash

sudo pacman -S --needed base-devel

if ! command -v cargo >/dev/null 2>&1; then
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..
rm ./paru -rf
