general {
    gaps_in             = 0
    gaps_out            = 0
    border_size         = 2
    col.active_border   = 0xFFC4A7E7
    col.inactive_border = 0xFF1F1F28
    layout              = dwindle
    allow_tearing       = true

    snap {
        enabled      = true
        window_gap   = 10
        monitor_gap  = 10
        respect_gaps = true
    }
}

group {
    col.border_active   = 0xFFC4A7E7
    col.border_inactive = 0xFF1F1F28

    groupbar {
        font_family   = IosevkaTerm Nerd Font Mono
        font_size     = 14
        render_titles = false


        indicator_gap    = 0
        indicator_height = 10

        gaps_in  = 0
        gaps_out = 0

        col.active   = 0xFFA8C3DD
        col.inactive = 0xFF1F1F28
    }
}

dwindle {
    pseudotile     = true
    preserve_split = true
    smart_split    = false
    force_split    = 2
}

decoration {
    rounding = 0

    dim_special = 0.3

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

animations {
    enabled = no
}

misc {
    font_family             = Courier Prime Code
    force_default_wallpaper = 0
    disable_hyprland_logo   = true

    # on_focus_under_fullscreen = 1

    mouse_move_enables_dpms = true
    key_press_enables_dpms  = true
    enable_anr_dialog       = true
}
