windowrule = float, class:calc
windowrule = pin, class:calc
windowrule = size 70% 50%, class:calc

windowrule = float, class:steam_app_1551360

windowrule = renderunfocused, title:Minecraft.*

windowrule = float, class:org.pulseaudio.pavucontrol
windowrule = center, class:org.pulseaudio.pavucontrol
windowrule = size 1000 700, class:org.pulseaudio.pavucontrol

windowrule = float, class:nvim-anywhere
windowrule = size 900 300, class:nvim-anywhere
windowrule = center, class:nvim-anywhere

windowrule = float, title:Save.*
windowrule = center, title: Save.*
windowrule = size 1000 700, title: Save.*

windowrule = suppressevent activate, title:.*Picture-in-Picture.*
windowrule = nodim , title:.*Picture-in-Picture.*
# windowrule = float, title:.*Picture-in-Picture.*
# windowrule = pin, title:.*Picture-in-Picture.*
# windowrule = bordersize 0, title:.*Picture-in-Picture.*

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

