windowrule = workspace $ws01, class:zen
# windowrule = workspace $ws02, class:com.mitchellh.ghostty
windowrule = workspace $ws03, class:org.pwmt.zathura
windowrule = workspace $ws04, class:cs2
windowrule = workspace $ws04, class:steam_app_.*
windowrule = workspace $ws04, class:(?i).*minecraft.*
windowrule = workspace $ws05 silent, class:steam
windowrule = workspace $ws05, class:net.lutris.Lutris
windowrule = workspace $ws06, class:vivaldi-stable
windowrule = workspace $ws07, class:thunderbird
windowrule = workspace $ws08, class:Spotify
windowrule = workspace $ws09, class:discord
windowrule = workspace $ws09, class:vesktop

windowrule = workspace special:specialwork, class:kittynvimscratch

windowrule = workspace $ws04, class:discovery.exe # The Finals

windowrule = float, class:calc
windowrule = pin, class:calc
windowrule = size 70% 50%, class:calc

windowrule = focusonactivate, class:zen
windowrule = float, class:steam_app_1551360

windowrule = float, class:org.pulseaudio.pavucontrol
windowrule = center, class:org.pulseaudio.pavucontrol
windowrule = size 1000 700, class:org.pulseaudio.pavucontrol

windowrule = float, class:loki

windowrule = float, class:org.gnome.gedit
windowrule = size 900 300, class:org.gnome.gedit
windowrule = center, class:org.gnome.gedit

windowrule = float, class:nvim-anywhere
windowrule = size 900 300, class:nvim-anywhere
windowrule = center, class:nvim-anywhere

windowrule = float, title:Save.*
windowrule = center, title: Save.*
windowrule = size 1000 700, title: Save.*

windowrule = suppressevent activate, title:.*Picture-in-Picture.*
windowrule = nodim , title:.*Picture-in-Picture.*
windowrule = workspace $ws10 silent, title:.*Picture-in-Picture.*
# windowrule = float, title:.*Picture-in-Picture.*
# windowrule = pin, title:.*Picture-in-Picture.*
# windowrule = bordersize 0, title:.*Picture-in-Picture.*

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


# windowrule = noblur, tag:hyprdrag-move
# windowrule = noblur, tag:hyprdrag-resize
# windowrule = opacity 0.50 override, tag:hyprdrag-move
# windowrule = opacity 0.80 override, tag:hyprdrag-resize
# windowrule = bordersize 5, tag:hyprdrag-move
# windowrule = bordersize 5, tag:hyprdrag-resize
# windowrule = bordercolor rgba(ffa726ee) rgba(ffeb3bee) 120deg, tag:hyprdrag-move
# windowrule = bordercolor rgba(ffcc80ee) rgba(fff9c4dd) 120deg, tag:hyprdrag-resize
