workspace = $ws01, defaultName:一, monitor:HDMI-A-1,   default:true
workspace = $ws02, defaultName:二, monitor:HDMI-A-1
workspace = $ws03, defaultName:三, monitor:HDMI-A-1
workspace = $ws04, defaultName:四, monitor:HDMI-A-1
workspace = $ws05, defaultName:五, monitor:HDMI-A-1
workspace = $ws06, defaultName:六, monitor:HDMI-A-1
workspace = $ws07, defaultName:七, monitor:HDMI-A-1
workspace = $ws08, defaultName:八, monitor:HDMI-A-1
workspace = $ws09, defaultName:九, monitor:HDMI-A-1
workspace = $ws10, defaultName:十, monitor:eDP-1,      default:true

windowrule = workspace $ws01, class:firefox

windowrule = workspace $ws02, class:com.mitchellh.ghostty
# windowrule = workspace $ws02, class:Alacritty

windowrule = workspace $ws04, title:Minecraft.*
windowrule = workspace $ws04, class:cs2
windowrule = workspace $ws04, class:worldofwarships64.exe
windowrule = workspace $ws04, class:forzahorizon5.exe
windowrule = workspace $ws04, class:overwatch.exe
windowrule = workspace $ws04, class:discovery.exe # The Finals

windowrule = workspace $ws05, class:steam

windowrule = workspace $ws06, class:org.mozilla.Thunderbird

windowrule = workspace $ws08, class:spotify

windowrule = workspace $ws09, class:discord
windowrule = workspace $ws09, class:vesktop

windowrule = workspace $ws10 silent, title:Picture-in-Picture

windowrule = workspace special:specialwork, class:com.mitchellh.ghostty.scratch


# workspace = w[tv1], bordersize:0

workspace = $ws01, gapsout:0, gapsin:0
# workspace = w[tv1]r[1-1], bordersize:0

workspace = s[1], gapsout:100, gapsin:0, bordersize:2
windowrule = rounding 10, floating:1
