[general]
working_directory = "/home/fuyu147/"
import = [
  "~/.config/alacritty/gruvbox.toml"
]

[window]
opacity = 0.95
# blur = true
dynamic_padding = true

[font]
normal = { family = "Miracode" }

[keyboard]
bindings = [
    { key = ")", mods = "Control", mode = "AppCursor", action = "ResetFontSize" },
]
