; =========================
; Polybar config
; Workspaces, tray, clock
; =========================

[colors]
background = #191724
foreground = #e0def4
active   = #ebbcba
inactive = #6e6a86

[bar/main]
width = 100%
height = 40
monitor = DP-4

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = IosevkaTerm NFM:size=18;2

modules-left  = workspaces
modules-right = tray clock

enable-ipc = true

tray-position = right
tray-padding = 6

; -------------------------
; Modules
; -------------------------

[module/workspaces]
type = internal/xworkspaces

pin-workspaces = false
enable-click = true
enable-scroll = true

label-active = %name%
label-active-background = ${colors.active}
label-active-foreground = ${colors.background}
label-active-padding = 2

label-occupied = %name%
label-occupied-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.inactive}
label-empty-padding = 2

[module/tray]
type = internal/tray
tray-spacing = 6

[module/clock]
type = internal/date
interval = 1
date = %Y-%m-%d
time = %H:%M:%S
label = %date% %time%
