#!/usr/bin/bash
printf '\e[?7l'

# get active window address
active=$(hyprctl activewindow -j | jq -r .address)

hyprctl clients -j \
| jq -r '.[] | [.address, .class, (.xwayland|tostring), .workspace.id, .title] | @tsv' \
| sort -k5,5n \
| awk -F'\t' -v active="$active" '
{
    mark = ($1 == active ? "*" : " ")
    # $1 = address, skip printing it
    printf "%s class: %20s   xwayland: %6s   workspace: %3s   title: %s\n",
           mark, $2, $3, $4, $5
}'

printf '\e[?7h'
