#!/usr/bin/bash
printf '\e[?7l'

active=$(hyprctl activewindow -j | jq -r .address)

hyprctl clients -j \
| jq -r '.[] | [.address, .class, (.xwayland|tostring), .workspace.id, .title] | @tsv' \
| sort -k4,4n -k2,2 \
| awk -F'\t' -v active="$active" '
NR==1 { max_class=0 }
{
    class=$2
    if (length(class) > max_class) max_class = length(class)
    data[NR]=$0
}
END {
    for (i=1; i<=NR; i++) {
        split(data[i], f, "\t")
        mark = (f[1] == active ? "*" : " ")
        printf "%s class: %-" max_class "s   xwayland: %6s   workspace: %3s   title: %s\n",
               mark, f[2], f[3], f[4], f[5]
    }
}'
printf '\e[?7h'
