#!/usr/bin/env bash

aur=(
    visual-studio-code-bin
    gemini-cli
    downgrade
    anki-bin
    cnijfilter2 # canon printer drivers
    evince-no-gnome
    fcitx5-mozc-ut
    localsend-bin # share files locally
    ttf-iosevka-term
    lorien-bin
    minecraft-launcher
    # protontricks # needed it to install webview for Forza Horizon
    # quickshell
    # r2modman-bin # thunderstore thing for linux
    rose-pine-cursor
    spicetify-cli
    # thorium-browser-bin
    timg # view img in terminal
    # ttf-comic-sans
    vesktop-bin
    wlogout
    wlrobs # plugin for OBS to record in wayland
    # zen-browser-bin
)

pkgs=(
    ghostty
    aspnet-runtime
    base-devel
    bat
    breeze
    udiskie
    keyd
    node
    breeze5
    brightnessctl
    btop
    cantor
    loupe
    chafa
    # niri
    fzf
    prismlauncher
    eza
    # cinnamon
    ckb-next
    clang
    cliphist
    fd
    # cuda
    discord
    dotnet-runtime
    dotnet-sdk
    dunst
    # elixir
    # erlang
    thunar
    eza
    fastfetch
    fcitx5-configtool
    bun
    fcitx5-gtk
    fcitx5-chinese-addons
    firefox
    fzf
    gedit
    geogebra
    jq
    ghostty
    gimp
    git
    github-cli
    gitui
    glfw
    gnome-clocks
    gnome-keyring
    gnome-weather
    go
    godot-mono
    gopls
    waybar
    grim
    gtk-engine-murrine
    gvfs # dependency for Thunar's volume management
    gwenview
    htop
    hyprland
    hyprlock
    hyprpicker
    hyprpolkitagent
    hyprshot
    jdk-openjdk
    keyd
    kitty
    komikku
    lazygit
    libreoffice-still
    loupe # gnome's image viewer
    lua
    # maven
    # mercurial
    # ncdu   # WinDirStat like tool
    # ncspot # TUI for spotify
    # ncurses
    neovim
    networkmanager
    network-manager-applet
    network-manager-applet
    noto-fonts-cjk
    noto-fonts
    npm
    nvtop
    nwg-look
    obs-studio
    odin
    openrgb
    pandoc-cli
    pavucontrol
    php
    power-profiles-daemon
    proton-vpn-gtk-app
    qalculate-gtk
    qbittorrent
    qt5ct
    qt5-wayland
    qt6-wayland
    ranger
    raylib
    ripgrep
    rofi-calc
    rofi-emoji
    rofi-wayland
    rsync
    rustup
    seahorse
    shfmt
    skim
    spotify-launcher
    steam
    steam-native-runtime
    swww
    tesseract
    tesseract-data-chi_sim
    tesseract-data-eng
    tesseract-data-jpn
    texlive-basic
    texlive-bibtexextra
    texlive-binextra
    texlive-fontsrecommended
    texlive-lang
    texlive-latex
    texlive-latexextra
    texlive-latexrecommended
    texlive-luatex
    texlive-mathscience
    texlive-plaingeneric
    texlive-xetex
    thefuck
    thunar
    thunar-volman # dependency for Thunar's volume management
    thunderbird
    tmux
    ttf-fira-code
    ttf-iosevkaterm-nerd
    ttf-nerd-fonts-symbols-mono
    tumbler # needed to display thumbnails in Thunar
    typst
    vlc
    vlc-plugins-all
    vlc-plugin-x264
    waybar
    wev
    wine
    wine-mono
    wl-clipboard
    xdg-desktop-portal-hyprland
    xournalpp
    yarn
    yazi
    zathura
    zathura-pdf-poppler
    zig
    zls
    zsh
)

case "$1" in
"v" | "vim")
    nvim "$0"
    ;;
*)
    paru -Syu
    paru -S --needed "${pkgs[@]}"
    paru -S --needed "${aur[@]}"
    ;;
esac
