unbind C-b
set-option -g prefix C-a
bind-key C-e send-prefix

set-option -g default-shell /bin/zsh

set -g default-terminal "xterm-256color"
set -as terminal-features ',xterm-256color:italics,usstyle'
set -s escape-time 0
set -g renumber-windows on
set -g base-index 1

# set -g status-left "   #[fg=grey] #S | #{?client_prefix,#[fg=blue](¬■‿■),#[fg=grey]( •‿•)} "
# set -g status-right '#(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '\''/state:/ {s=$2} /percentage:/ {p=$2} END {if (s != "charging" && s != "fully-charged") print "| " p " (" s ")"}'\'')'
set -g status-left "#S > "
set -g status-right "%H:%M"
set -g status-style "fg=#e0d6c3"
set -g window-status-current-format "#{?client_prefix,#[fg=blue]¬,#[fg=grey]}#[fg=#6A9589][#[fg=#7E9CD8]#I:#W#[fg=#6A9589]]#[fg=#e0d6c3]"
set -g window-status-format " #I:#W "
set -g status-justify left
set-option -g status-position top
set-option -g status-left-length 30
set-option -g status-right-length 70

bind o copy-mode
unbind -T copy-mode Enter
bind -T copy-mode Enter send-keys -X copy-selection
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe 'wl-copy'

bind "v" split-window -v
bind "h" split-window -h

bind r run-shell "tmux source ~/.tmux.conf"

bind g run-shell "code ."
bind y split-window -v "yazi"
bind q run-shell "kitty sh -c ranger"

bind k split-window -v "make; exec $SHELL"

bind-key -r C-t run-shell "tmux-goway"
bind-key -r t run-shell "tmux-goway"

bind-key -r l run-shell "tmux-goway -p"
bind-key -r C-l run-shell "tmux-goway -p"
